### ISSUE TITLE
JPEG minithumbnail error

### ISSUE THREAD

**Issue by cavallium** [tdlight-team/tdlight#7]
[ 1][t24][1609642107.754322767][Photo.cpp:398][#6][!Td]	Receive unexpected JPEG minithumbnail

**Comment by andrew-ld** [comment]
https://github.com/tdlight-team/tdlight/commit/c66972354af5c89867e67c2440572b7811c5b1f1

**Comment by cavallium** [comment]
After the patch: [ 1][t24][1609677600.002752542][Photo.cpp:398][#6][!Td]	Receive unexpected JPEG minithumbnail

**Comment by andrew-ld** [comment]
not a bug, this is a side-effect of "disable_minithumbnails"

https://github.com/tdlight-team/tdlight/blob/49c2bbd9b52693889c59ec129ada3e2aba6a29a6/td/telegram/Photo.cpp#L397

since we deactivate the saving of previews, tdlib doesn't know if it is there or not, so if it receives it and thinks it shouldn't be there, it doesn't know what to do, it would be enough to remove the log, it is good as it is.

https://github.com/tdlight-team/tdlight/blob/49c2bbd9b52693889c59ec129ada3e2aba6a29a6/td/telegram/Photo.cpp#L398
